version: '3'
services:
  langchain-streamlit-agent:
    image: applied-ai-rag-assistant:latest
    build: ./app
    command: streamlit run rag_assistant/Hello.py --server.port 8051
    volumes:
      - ./rag_assistant/:/app/rag_assistant
    ports:
      - 8051:8051